name: Run tests in Docker

on:
  push:
    branches: [ "main" ]

env:
   DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} # Docker username secret
   DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} # Docker password secret

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t myimage . -f Dockerfile.txt

    - name: Log in to Docker registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to registry
      run: |
        docker tag myimage ${{ secrets.DOCKER_USERNAME }}/selenium-training-project
        docker push ${{ secrets.DOCKER_USERNAME }}/selenium-training-project

    - name: Run tests in Docker container
      run: docker run selenium-training-project/myimage

    - name: Collect test results
      run: |
        # collect and display test results
